# Site settings
title: Manjitha Perera Data Science Portfolio
description: Showcasing projects, skills, and experience in data science, machine learning, and software development.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: m-perera.github.io # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: manjitha perera
user_description: Currently pursuing a Masters degree in Data Science, with a strong emphasis on machine learning, statistical modeling, and data visualization. Along with the projects listed below, I am currently working on a new project that focuses on E-Commerce Sales Forecasting. This includes working with and manipulating time series data to create a predictive model for sales trends, as well as creating an interactive sales dashboard in Tableau. Stay tuned for the project, which will be available soon! 
user_description: I am constantly experimenting with new techniques and methodologies in order to stay on the cutting edge of data science through hands-on projects and real-world applications.
user_title: Msc Data Science
email: 
twitter_username: lorem_ipsum
github_username:  m-perera
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']









