# Site settings
title: Manjitha Perera Data Science Portfolio
description: Showcasing projects, skills, and experience in data science, machine learning, and software development.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: m-perera.github.io # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: manjitha perera
user_description: Wite something about you
user_title: Msc Data Science
email: 
twitter_username: lorem_ipsum
github_username:  m-perera
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
