# Site settings
title: Manjitha Perera Data Science Portfolio
description: Showcasing projects, skills, and experience in data science, machine learning, and software development.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: m-perera.github.io # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: manjitha perera
user_description: I am currently pursuing a Master’s degree in Data Science, with a strong focus on machine learning, statistical modeling, and data visualization. As part of my learning journey, I’m deeply engaged in an exciting and ambitious project: building my own GPT model from scratch, following Andre Karpathy’s detailed approach. This project is allowing me to dive deep into neural networks, natural language processing, and deep learning, as I experiment with custom architectures, model training, and fine-tuning to create a more personalized and efficient system.I’m constantly exploring new techniques, methodologies, and technologies to stay at the forefront of data science. Through each project, I aim to not only expand my technical expertise but also cultivate a mindset of continuous learning and innovation. I’m excited to share more about the GPT project once it’s ready!!
user_title: Msc Data Science
email: 
twitter_username: lorem_ipsum
github_username:  m-perera
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']









